# Generated by Django 5.0.3 on 2024-03-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_to_text', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img2text',
            old_name='text',
            new_name='extracted_text',
        ),
    ]
