# Generated by Django 5.0.3 on 2024-03-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_to_text', '0002_rename_text_img2text_extracted_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img2text',
            name='image',
            field=models.URLField(),
        ),
    ]
